const salons = [
  {
    id: 0,
    name: 'Long Hair Salon',
    address: '123 Beauty Ave',
    city: 'Fort Worth',
    state: 'TX',
    zip_code: '76110',
    phone_number: '222-555-1234',
    email: 'contact@longhair.com',
  },
  {
    id: 1,
    name: 'Elegant Salon',
    address: '123 Beauty Ave',
    city: 'Beautyville',
    state: 'CA',
    zip_code: '90210',
    phone_number: '222-555-1234',
    email: 'contact@elegantsalon.com',
  },
  {
    id: 2,
    name: 'Style Hub',
    address: '456 Fashion Blvd',
    city: 'Glam City',
    state: 'NY',
    zip_code: '10001',
    phone_number: '888-555-5678',
    email: 'info@stylehub.com',
  },
  {
    id: 3,
    name: 'Chic Cuts',
    address: '789 Trendy St',
    city: 'Stylestown',
    state: 'TX',
    zip_code: '75001',
    phone_number: '888-555-8765',
    email: 'hello@chiccuts.com',
  },
  {
    id: 4,
    name: 'Lux Looks',
    address: '321 Glamour Ln',
    city: 'Shine City',
    state: 'FL',
    zip_code: '33101',
    phone_number: '888-555-4321',
    email: 'contact@luxlooks.com',
  },
  {
    id: 5,
    name: 'Beauty Bliss',
    address: '654 Elegance Dr',
    city: 'Radiant Town',
    state: 'NV',
    zip_code: '89109',
    phone_number: '777-555-2345',
    email: 'info@beautybliss.com',
  },
  {
    id: 6,
    name: 'Glow Up Salon',
    address: '987 Shine Ave',
    city: 'Bright City',
    state: 'WA',
    zip_code: '98101',
    phone_number: '777-555-6789',
    email: 'support@glowupsalon.com',
  },
]

export default salons
